kind: Service
apiVersion: v1
metadata:
  name: transactions-reader
spec:
  selector:
    app: transactions-reader
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-reader
spec:
  selector:
      matchLabels:
        app: transactions-reader
  replicas: 1
  template:
    metadata:
      labels:
        app: transactions-reader
    spec:
      containers:
        - name: transactions-reader
          image: transactions-reader:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
